#!/usr/bin/env python

import rospy
from std_msgs.msg import String

class DrawCircleNode:
    def __init__(self):
        rospy.init_node('draw_circle_node')
        self.pub = rospy.Publisher('/task_status/draw_circle', String, queue_size=10)
        self.rate = rospy.Rate(1)  # 1 Hz

    def run(self):
        while not rospy.is_shutdown():
            # Perform the task (e.g., drawing a circle)
            # ...

            # Publish status
            self.pub.publish('active')
            self.rate.sleep()

if __name__ == '__main__':
    node = DrawCircleNode()
    node.run()
